# -*- coding: utf-8 -*-
"""python_findanagrams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_IZmcF2hrgymT3Etq9VWrjMqTQetDTsz
"""

"""
Developer Name: Mandela Thomas
Developer Email: mthomas232@atsmas.com
Developer Website: www.atsmas.com
Developer Github: https://github.com/mandelathomas
Developer Linkedin:https://www.linkedin.com/in/mandela-philip-thomas/
Project Date : July 30, 2026
Project Name : Basic Python
Project Description : Loading and working text files

"""


#import various libraries
import pandas as pd #Data manipulation
import numpy as np
import matplotlib.pyplot as plt #visualization
import seaborn as sns #visualization
import math
import datetime
import collections
import pydantic  #data validation

#---reading and manipulating the file ----


#Reading encode

#create an empyty list
messages = []

##copy the loaded file to the empty list
#loope  over the file and remove any whitespace using strip

for info in open('/content/words.txt'):
    messages.append(info.strip().lower())

print(len(messages))

#show the first 10 values in the dataset
messages[0:10]

#arranging the data by sorting it
messages.sort()
print(messages)

''.join(sorted('aaron'))

def signature(word):
    return ''.join(sorted(word))

signature('python')

words_by_sig = collections.defaultdict(list)
for word in messages:
    words_by_sig[signature(word)].append(word)